version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stockdata_webapp_team16_image
    container_name: stockdata_webapp_team16
    ports:
      - "5001:5001"
    volumes:
      - .:/stockapp
    environment:
      FLASK_DEBUG: "1"